apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-test
  namespace: default
spec:
  selector:
    matchLabels:
      run: go-rest-test
  template:
    metadata:
      labels:
        run: go-rest-test
    spec:
      containers:
      - image: gcr.io/jaisor-kube-learn/jaisor-go-rest-test:v1
        imagePullPolicy: IfNotPresent
        name: go-rest-test
        ports:
        - containerPort: 8090
          protocol: TCP