apiVersion: v1
kind: Service
metadata:
  name: go-rest-test
  namespace: default
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: go-rest-test
  type: NodePort